cmake_minimum_required(VERSION 3.8)
project(jetpilot_planning_manager)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ament_cmake_auto REQUIRED)
ament_auto_find_build_dependencies()
ament_auto_add_library(${PROJECT_NAME}_node SHARED src/planning_manager_node.cpp)
target_compile_features(${PROJECT_NAME}_node PUBLIC cxx_std_17)
ament_auto_add_executable(planning_manager_node src/planning_manager_node_main.cpp)
target_compile_features(planning_manager_node PUBLIC cxx_std_17)
target_link_libraries(planning_manager_node ${PROJECT_NAME}_node)
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_auto_package(USE_SCOPED_HEADER_INSTALL_DIR)
