<?xml version="1.0"?>
<package format="3">
  <name>jetpilot_system_launch</name>
  <version>0.0.1</version>
  <description>JetPilot system launch</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <test_depend>ament_cmake_pytest</test_depend>

  <exec_depend>custom_joy_node</exec_depend>
  <exec_depend>jetpilot_bag_tools</exec_depend>
  <exec_depend>jetpilot_controller</exec_depend>
  <exec_depend>jetpilot_hdmap_publisher</exec_depend>
  <exec_depend>jetpilot_e2e_inference</exec_depend>
  <exec_depend>jetpilot_localization_manager</exec_depend>
  <exec_depend>jetpilot_operation</exec_depend>
  <exec_depend>jetpilot_planning</exec_depend>
  <exec_depend>jetpilot_teleop_tools</exec_depend>
  <exec_depend>jetpilot_rtp_tools</exec_depend>
  <exec_depend>openeb_ros2</exec_depend>
  <exec_depend>pca9685_rc_driver</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rc_serial_reader</exec_depend>
  <exec_depend>jetpilot_vesc_interface</exec_depend>
  <exec_depend>isaac_ros_launch_utils</exec_depend>
  <exec_depend>isaac_ros_jetson_stats</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rosbag2</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>vslam_map_tools</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
