/**:
  ros__parameters:
    output_dir: "/workspaces/record"
    storage_id: mcap
    all_topics: false
    topics:
      - /scan
      - /realsense/color/image_raw
      - /realsense/color/camera_info
      - /realsense/left/image_rect
      - /realsense/left/camera_info_rect
      - /realsense/right/image_rect
      - /realsense/right/camera_info_rect
      - /vehicle/control_cmd
      - /vehicle/vesc/commands/motor/speed
      - /vehicle/vesc/commands/servo/position
      - /vehicle/vesc/sensors/core
      - /vehicle/vesc/sensors/imu
      - /vehicle/vesc/sensors/imu/raw
      - /vehicle/vesc/sensors/servo_position_command
      - /teleop/selected_target_drive
      - /autonomous/target_drive
      - /emergency/target_drive
