const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const projector = app.slice(app.indexOf('function mapPointProjector('), app.indexOf('\nfunction ', app.indexOf('function mapPointProjector(') + 1));
const detail = {map:{path:'/map/a'}, point_cloud_url:'/points', raster:{width:100,height:100,resolution_m_per_px:0.1,origin_xy_yaw:[2,3,Math.PI/2]}};
const sandbox = {state:{selectedMapDetail:detail,mapLayers:{landmark:true}}, document:{getElementById:()=>null},requestAnimationFrame:()=>1,esc:String,drawMapPreview:()=>{},console};
vm.createContext(sandbox);
vm.runInContext(projector + '\n' + fs.readFileSync(path.join(root,'point_cloud_ui.js'),'utf8'), sandbox);
sandbox.data = {version:1,total_points:3,raster:detail.raster,points:[[1,4,0.1],[1,4,1.2],[1,4,0.3]]};
vm.runInContext('validatePointCloud(data,state.selectedMapDetail.raster); const v=pointCloudState(state.selectedMapDetail); v.data=data; v.mode=true; v.min=0.1; v.max=1.2; v.low=0.1; v.high=0.3;', sandbox);
const drawn=[];
sandbox.ctx={fillRect:(...args)=>drawn.push(args)};
vm.runInContext("pointCloudView.style='points'; drawPointCloud(ctx,state.selectedMapDetail,100,100)",sandbox);
assert.equal(drawn.length,2,'height filtering keeps two low points at same XY');
assert.ok(Math.abs(drawn[0][0]-10)<1e-8);
assert.ok(Math.abs(drawn[0][1]-89)<1e-8,'map origin and yaw match existing line projection');
vm.runInContext("setPointCloudHeight('low',1.2)",sandbox);
assert.equal(vm.runInContext('pointCloudView.high',sandbox),1.2,'crossed bounds remain valid');
assert.throws(()=>vm.runInContext('validatePointCloud({...data,raster:{...data.raster,width:200}},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,points:[[0,0,NaN]]},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,issue:"missing TF"},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,points:[]},state.selectedMapDetail.raster)',sandbox));
// Density preserves coincident points rather than collapsing them to one mark.
vm.runInContext("pointCloudView.style='density'; pointCloudView.low=0.1; pointCloudView.high=0.3",sandbox);
const density = vm.runInContext('pointCloudDensity(state.selectedMapDetail,pointCloudView)',sandbox);
assert.equal(density.count,2);
assert.equal(density.cells.size,1);
assert.equal([...density.cells.values()][0],2);
assert.ok(vm.runInContext('pointCloudDensityAlpha(8,8,1.8) > pointCloudDensityAlpha(1,8,1.8)',sandbox));
assert.ok(vm.runInContext('pointCloudDensityAlpha(1,4,3) < pointCloudDensityAlpha(1,4,1)',sandbox));
const marks=[];
sandbox.ctx={fillRect(...rect){marks.push({rect,color:this.fillStyle});}};
vm.runInContext('drawPointCloud(ctx,state.selectedMapDetail,100,100)',sandbox);
vm.runInContext('drawPointCloud(ctx,state.selectedMapDetail,200,200)',sandbox);
assert.equal(marks[0].color,marks[1].color,'zoom does not change brightness');
marks[0].rect.forEach((value,i)=>assert.equal(marks[1].rect[i],value*2));
assert.equal(vm.runInContext('pointCloudView.densityCache',sandbox),density,'density is cached during redraws');
vm.runInContext('setPointCloudHeight("high",1.2)',sandbox);
assert.equal(vm.runInContext('pointCloudDensity(state.selectedMapDetail,pointCloudView).count',sandbox),3);
vm.runInContext('setPointCloudDensityOption("cellSizeM",0.1)',sandbox);
assert.equal(vm.runInContext('pointCloudDensity(state.selectedMapDetail,pointCloudView).cellPx',sandbox),1);
marks.length=0;
vm.runInContext('state.mapLayers.landmark=false; drawPointCloud(ctx,state.selectedMapDetail,100,100)',sandbox);
assert.equal(marks.length,0,'hidden layer remains hidden in density mode');
vm.runInContext(`pointCloudView.data={...data,points:[[1,4,0.2],[1000,1000,0.2]]}; pointCloudView.low=0.1;pointCloudView.high=0.3`,sandbox);
assert.equal(vm.runInContext('pointCloudDensity(state.selectedMapDetail,pointCloudView).count',sandbox),1,'off-raster points are excluded');
vm.runInContext('pointCloudView.low=2; pointCloudView.high=3',sandbox);
assert.equal(vm.runInContext('pointCloudDensity(state.selectedMapDetail,pointCloudView).cells.size',sandbox),0,'empty height slice is valid');
vm.runInContext("pointCloudState({map:{path:'/map/b'},point_cloud_url:'/other'})",sandbox);
assert.equal(vm.runInContext('pointCloudView.data',sandbox),null,'switching maps releases old points');
assert.equal(vm.runInContext('pointCloudView.densityCache',sandbox),null);
assert.equal(vm.runInContext('pointCloudView.style',sandbox),'density','new point cloud defaults to density');
console.log('Point cloud UI: density, contrast, zoom, cache, filter, projection and map switching OK');
