const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const projector = app.slice(app.indexOf('function mapPointProjector('), app.indexOf('\nfunction ', app.indexOf('function mapPointProjector(') + 1));
const detail = {map:{path:'/map/a'}, point_cloud_url:'/points', raster:{width:100,height:100,resolution_m_per_px:0.1,origin_xy_yaw:[2,3,Math.PI/2]}};
const sandbox = {state:{selectedMapDetail:detail,mapLayers:{landmark:true}}, document:{getElementById:()=>null},requestAnimationFrame:()=>1,esc:String,drawMapPreview:()=>{},console};
vm.createContext(sandbox);
vm.runInContext(projector + '\n' + fs.readFileSync(path.join(root,'point_cloud_ui.js'),'utf8'), sandbox);
sandbox.data = {version:1,total_points:3,raster:detail.raster,points:[[1,4,0.1],[1,4,1.2],[1,4,0.3]]};
vm.runInContext('validatePointCloud(data,state.selectedMapDetail.raster); const v=pointCloudState(state.selectedMapDetail); v.data=data; v.mode=true; v.min=0.1; v.max=1.2; v.low=0.1; v.high=0.3;', sandbox);
const drawn=[];
sandbox.ctx={fillRect:(...args)=>drawn.push(args)};
vm.runInContext('drawPointCloud(ctx,state.selectedMapDetail,100,100)',sandbox);
assert.equal(drawn.length,2,'height filtering keeps two low points at same XY');
assert.ok(Math.abs(drawn[0][0]-10)<1e-8);
assert.ok(Math.abs(drawn[0][1]-89)<1e-8,'map origin and yaw match existing line projection');
vm.runInContext("setPointCloudHeight('low',1.2)",sandbox);
assert.equal(vm.runInContext('pointCloudView.high',sandbox),1.2,'crossed bounds remain valid');
assert.throws(()=>vm.runInContext('validatePointCloud({...data,raster:{...data.raster,width:200}},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,points:[[0,0,NaN]]},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,issue:"missing TF"},state.selectedMapDetail.raster)',sandbox));
assert.throws(()=>vm.runInContext('validatePointCloud({...data,points:[]},state.selectedMapDetail.raster)',sandbox));
vm.runInContext("pointCloudState({map:{path:'/map/b'},point_cloud_url:'/other'})",sandbox);
assert.equal(vm.runInContext('pointCloudView.data',sandbox),null,'switching maps releases old points');
console.log('Point cloud UI: filter, projection, bounds, invalid data and map switching OK');
