teleop_button_manager_node:
  ros__parameters:
    auto_button: 0
    manual_button: 3
    stop_button: 1
    back_button: 6
    bag_start_button: 5
    bag_stop_button: 4
    steer_offset_inc_button: 15
    steer_offset_dec_button: 14
    hold_time_s: 1.0
