teleop_cmd_node:
  ros__parameters:
    steering_axis: 0
    throttle_axis: 5
    brake_axis: 2
    deadman_button: 4
    steering_scale: 1.0
    throttle_scale: 1.0
    brake_scale: 1.0
    deadzone: 0.05
    trigger_min: -1.0
    trigger_max: 1.0
